sequenceDiagram
    participant Service
    participant DBProxy
    participant DBConfigure
    participant SQLConfigure
    participant DB
    DBProxy->>DBConfigure: Get DB Configure
    DBProxy->>SQLConfigure:  Get Sql Configure
    Service->>DBProxy: Commit
    Note right of Service: Request Need:<br/> Sql_id and params
    Note right of DBProxy: Construct SQL:<br/>found sql_id in Sql<br/> Configure, and <br/>replace params ,<br/> get the db_id
    DBProxy->>DB: Found db_id in db configure ,call db 
    DB->>DBProxy: Return results
    DBProxy->>Service:  Return Packaging data
